def kindOftriangle():
    """
    This function returns a list of the sides of a triangle given by
    the user, if it is possible to construct a triangle, or, otherwise,
    prints a message that it is impossible to construct a triangle
    with them.
    :return:
    """
    lt = []
    a = int(input("Digit the value of the first side: "))
    b = int(input("Digit the value of the second side: "))
    c = int(input("Digit the value of the third side: "))
    if (a + b > c) and (a + c > b) and (b + c > a):
        lt.append(a)
        lt.append(b)
        lt.append(c)
        if a == b == c:
            print("This is a equilateral triangle.")
        if (a == b and a != c) or (a == c and a != b) or (b == c and b != a):
            print("This is a isosceles triangle.")
        if a != b and b != c and c != a:
            print("This is a escalene triangle. ")
        return lt
    else:
        asw = "It's impossible to construct a triangle with the sides given."
        return print(asw)


def triangleRectangle(lt, asw=''):
    """
    This function have as the return a print if it is triangle rectangle or not,
    taken the values from a list generated by function above or taking a
    parameter from the function above saying about impossibility to construt
    triangle.
    :param lt:
    :param asw:
    :return:
    """
    if not lt:
        return asw
    for i in range(0, len(lt)):
        if lt[i] ** 2 + lt[i + 1] ** 2 == lt[i + 2] ** 2:
            return print("It's a triangle rectangle.")
        return print("It's not a triangle rectangle")


triangleRectangle(kindOftriangle())
